// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bgKMZjYxNaBy8EkQoJ2cKWas80TI18Y',
    appId: '1:143537014188:web:25cef2a3490a66c1ea2609',
    messagingSenderId: '143537014188',
    projectId: 'detach-creo',
    authDomain: 'detach-creo.firebaseapp.com',
    storageBucket: 'detach-creo.firebasestorage.app',
    measurementId: 'G-7QW1EMGJCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfx-5FZuUk31IW4NzV5Bh7Xb6Q8nRsuc',
    appId: '1:143537014188:android:74e6e858b714ea9dea2609',
    messagingSenderId: '143537014188',
    projectId: 'detach-creo',
    storageBucket: 'detach-creo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAg4FqZ2q5XzcYXwJIbFEiYb6c2sgveM',
    appId: '1:143537014188:ios:c721daa8e4c41ad9ea2609',
    messagingSenderId: '143537014188',
    projectId: 'detach-creo',
    storageBucket: 'detach-creo.firebasestorage.app',
    iosBundleId: 'com.example.detach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIAg4FqZ2q5XzcYXwJIbFEiYb6c2sgveM',
    appId: '1:143537014188:ios:c721daa8e4c41ad9ea2609',
    messagingSenderId: '143537014188',
    projectId: 'detach-creo',
    storageBucket: 'detach-creo.firebasestorage.app',
    iosBundleId: 'com.example.detach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2bgKMZjYxNaBy8EkQoJ2cKWas80TI18Y',
    appId: '1:143537014188:web:f3eeffae46b6aef9ea2609',
    messagingSenderId: '143537014188',
    projectId: 'detach-creo',
    authDomain: 'detach-creo.firebaseapp.com',
    storageBucket: 'detach-creo.firebasestorage.app',
    measurementId: 'G-R09W2XB8ZR',
  );
}